### ISSUE TITLE
Sensor todo-list

### ISSUE THREAD

**Issue by Jad2wizard** [Jad2wizard/bim-gis#3]
- [ ] the UI of creating new sensor type
- [ ] the translation and rotation of sensors on the model
- [ ] rendering the sensor 3D model
